TheatreAssessment/Controllers/UserAdminstrationController.cs
using TheatreAssessment.Models;
using TheatreAssessment.ViewModels;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;


namespace TheatreAssessment.Controllers

{
    [Authorize(Roles = "Admin")]
    /// <summary>
    /// This controller manages users roles and admins
    /// </summary>
    public class UserAdminstrationController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        // GET: UserAdminstration
        public ActionResult Index()
        {
            List<UserViewModel> theUsers = new List<UserViewModel>();
            foreach(ApplicationUser aUser in db.Users)
            {
                UserViewModel uViewModel = new UserViewModel();
                uViewModel.ID = aUser.Id;
                uViewModel.UserName = aUser.UserName;
                uViewModel.Email = aUser.Email;
                uViewModel.IsAdmin = aUser.IsAdmin;
                uViewModel.IsSuspended = aUser.IsSuspended;
                theUsers.Add(uViewModel);
            }
            return View(theUsers);
        }

        // GET: UserAdminstration/Details/5
        public ActionResult Details(string id)
        {
            ApplicationUser aUser = db.Users.Single(m => m.Id == id);
            UserViewModel uvm = new UserViewModel();
            uvm.UserName = aUser.UserName;
            uvm.UserName = aUser.Email;
            uvm.IsAdmin = aUser.IsAdmin;
            uvm.IsSuspended = aUser.IsSuspended;

            return View(uvm);
        }

        // GET: UserAdminstration/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: UserAdminstration/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: UserAdminstration/Edit/5
        public ActionResult Edit(string id)
        {
            
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserViewModel uvm = new ViewModels.UserViewModel();
            ApplicationUser applicationUser = db.Users.Find(id);
            if(applicationUser == null)
            {
                return HttpNotFound();
            }
            else
            {
                uvm.UserName = applicationUser.UserName;
                uvm.Email = applicationUser.Email;
                uvm.IsAdmin = applicationUser.IsAdmin;
                uvm.IsSuspended = applicationUser.IsSuspended;
            }
            return View(uvm);
        }

        // POST: UserAdminstration/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(UserViewModel userViewModel)
        {
            var UserManager = new UserManager<ApplicationUser>(new Microsoft.AspNet.Identity.EntityFramework.UserStore<ApplicationUser>(db));
            ApplicationUser au = db.Users.Find(userViewModel.ID);
            au.Id = userViewModel.ID;
            au.UserName = userViewModel.UserName;
            au.Email = userViewModel.Email;
            au.IsAdmin = userViewModel.IsAdmin;
            au.IsSuspended = userViewModel.IsSuspended;

            if(ModelState.IsValid)
            {
                db.Entry(au).State = EntityState.Modified;
                if ((au.IsAdmin) && (UserManager.IsInRole(au.Id, "Admin")))
                    UserManager.AddToRole(au.Id, "Admin");
                else if ((!au.IsAdmin) && (UserManager.IsInRole(au.Id, "Admin")))
                    UserManager.RemoveFromRoles(au.Id, "Admin");
                db.SaveChanges();
                if ((au.IsSuspended) && (!UserManager.IsInRole(au.Id, "Restricted")))
                    UserManager.AddToRole(au.Id, "Restricted");
                else if ((!au.IsSuspended) && (UserManager.IsInRole(au.Id, "Restricted")))
                    UserManager.RemoveFromRoles(au.Id, "Restricted");

                return RedirectToAction("Index");
            }
            return View(userViewModel);
        }

        // GET: UserAdminstration/Delete/5
        public ActionResult Delete(string id)
        {
            UserViewModel uvm = new ViewModels.UserViewModel();
            ApplicationUser applicationUser = db.Users.Find(id);
            if(applicationUser == null)
            {
                return HttpNotFound();
            }
            else
            {
                uvm.ID = applicationUser.Id;
                uvm.UserName = applicationUser.UserName;
                uvm.Email = applicationUser.Email;
                uvm.IsAdmin = applicationUser.IsAdmin;
                uvm.IsSuspended = applicationUser.IsSuspended;
            }
            return View(uvm);
        }

        // POST: UserAdminstration/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            ApplicationUser applicationUser = db.Users.Find(id);
            db.Users.Remove(applicationUser);
            db.SaveChanges();

                return RedirectToAction("Index");
            
        }
    }
}

TheatreAssessment/Views/Shared/_AddComment.cshtml
@model TheatreAssessment.Models.Comment

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Comment</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.HiddenFor(model => model.PostID)
            @Html.HiddenFor(model => model.CommentID)
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CommentBody, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CommentBody, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CommentBody, "", new { @class = "text-danger" })
            </div>
        </div>



        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Add" class="btn btn-default" />
            </div>
        </div>
    </div>
}

TheatreAssessment/Views/Shared/_DeleteComment.cshtml
@model TheatreAssessment.Models.Comment
@using (Html.BeginForm("DeleteComment", "Posts"))
{
    @Html.AntiForgeryToken()
<div>
    <h4>Comment</h4>
    <hr />
    <dl class="dl-horizontal">
        @Html.HiddenFor(model => model.CommentID)
        @Html.HiddenFor(model => model.PostID)
        
        <dt>
            @Html.DisplayNameFor(model => model.CommentBody)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CommentBody)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CommentDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CommentDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserName)
        </dd>

    </dl>
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" />
        </div>
    
</div>
}

TheatreAssessment/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title Local Theatre</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <script type="text/javascript" src="@Url.Content("/Scripts/jquery-1.10.2.min.js")"></script>
    <link rel="stylesheet" type="text/css" href="@Url.Content("/Content/slick/slick.css")" />
    <link rel="stylesheet" type="text/css" href="@Url.Content("/Content/slick/slick-theme.css")" />
    <script type="text/javascript" src="@Url.Content("/Content/slick/slick.min.js")"></script>

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Glasgow Local Theatre", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Posts", "Index", "Posts")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    @if ((User.Identity.IsAuthenticated) && (User.IsInRole("Admin")))
                    {
                        <li>@Html.ActionLink("Adminstration","Index","UserAdminstration")</li>
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Local Theatre</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>